[package]
name = "capture-pipewire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ashpd = "0.6.8"
image = "0.24.8"
pipewire = "0.7.2"
tokio = { version = "1.35.1", features = ["full"] }
